# Generated by Django 3.2.6 on 2021-08-17 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licence',
            old_name='expiry_data',
            new_name='expiry_date',
        ),
    ]
