# Generated by Django 3.2.6 on 2021-08-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timeline',
            field=models.DateTimeField(null=True),
        ),
    ]
