# Generated by Django 3.2.6 on 2021-08-22 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_projects'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projects',
            table='project',
        ),
    ]
