# Generated by Django 3.2.6 on 2021-08-22 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_projects_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projecet_id',
            new_name='project_id',
        ),
    ]
