# Generated by Django 3.2.6 on 2021-10-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'table1',
            },
        ),
        migrations.CreateModel(
            name='table2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('age1', models.IntegerField()),
                ('time1', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'table2',
            },
        ),
    ]
