# Generated by Django 3.2.6 on 2021-08-27 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='board',
            table='board',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
    ]
